import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { run, run1 } from '@/fetching-data/data'
import Recipes from '@/components/recipes'




function Home(props) {
  console.log(props.recipes) // recipes data
  console.log(props.categories) // categories data

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={`${styles.main} ${inter.className}`}>

        <Recipes recipes={props.recipes} categories={props.categories}/>
       
        
      </main>
    </>
  )
}

export async function getStaticProps() {
  const docs = await run();

  // const filePath = path.join(process.cwd())
  // await fs.readFile();

  const docs1 = await run1();
  return {
    props: {
      recipes: docs,
      categories: docs1,
    },
    revalidate: 1800,
  }
}

export default Home;